# Generated by Django 4.0.3 on 2022-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='contactnumber',
            field=models.IntegerField(default=0),
        ),
    ]
