# Generated by Django 4.0.3 on 2022-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_stores_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('desc', models.CharField(default='No Desc', max_length=1000)),
            ],
        ),
    ]
