# Generated by Django 4.0.3 on 2022-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=20)),
                ('user_country', models.CharField(max_length=30)),
                ('user_zipcode', models.IntegerField()),
                ('useru_sername', models.CharField(max_length=50)),
                ('user_userpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
    ]
