# Generated by Django 4.0.3 on 2022-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_signup_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user_name',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
