# Generated by Django 4.0.3 on 2022-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_signup_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_city',
            new_name='user_address_city',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_country',
            new_name='user_address_country',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_state',
            new_name='user_address_state',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='useru_sername',
            new_name='user_username',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user_zipcode',
        ),
        migrations.AddField(
            model_name='signup',
            name='user_address_zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
