# Generated by Django 4.0.3 on 2022-04-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orders_items_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_address_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_userpassword',
            new_name='userpassword',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_address_zipcode',
            new_name='zip_code',
        ),
    ]
